import { useEffect, useState } from "react";
import { motion, useScroll, useSpring } from "framer-motion";
import { ArrowUpRight, ChevronDown, Github, Instagram, Linkedin, Menu, X, Send, Sparkles, Sun, Moon, Play, PenTool, Image, Film } from "lucide-react";
import axios from "axios";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const navItems = ["About", "Skills", "Creative Studio", "Projects", "Achievements", "Experience", "Education", "Certifications", "Contact"];
const projects = [
  { no: "01", title: "ScamShield", type: "AI · SAFETY · FLAGSHIP", desc: "An AI-powered WhatsApp fraud prevention assistant that helps people understand suspicious messages before they act.", tags: ["Python", "AI", "NLP"], href: "https://github.com/vadapallimouli/scamshield", accent: "teal", flow: "SCAN → SEND → ANALYZE → STAY SAFE" },
  { no: "02", title: "Medicine Scanner", type: "DATA · WEB APP", desc: "A practical medicine information experience built around structured data, search and clear information retrieval.", tags: ["Data", "Search", "Web"], accent: "blue" },
  { no: "03", title: "Attendance Management System", type: "SOFTWARE · LOGIC", desc: "A focused system for tracking attendance, calculating percentages and identifying students below thresholds.", tags: ["Java", "DSA", "Logic"], accent: "sand" },
  { no: "04", title: "Ticket Booking System", type: "WEB · INTERACTION", desc: "A web application for searching tickets, booking seats and tracking availability through a clear user flow.", tags: ["HTML", "CSS", "JavaScript"], accent: "blue" },
  { no: "05", title: "Patch-Based SVD Image Denoising", type: "IMAGE PROCESSING", desc: "Reducing image noise with Singular Value Decomposition while preserving the details that matter.", tags: ["Python", "NumPy", "Pillow"], accent: "teal" },
];
const skillGroups = [["Programming", "Python", "Java", "MATLAB"], ["Tools & Platforms", "Google Colab", "Jupyter Notebook", "VS Code"], ["AI & Data", "Data Analysis", "Machine Learning Fundamentals", "Data Visualization", "Artificial Intelligence Fundamentals"], ["Development", "Object-Oriented Programming", "Problem Solving", "Data Structures", "HTML", "CSS", "JavaScript"]];
const creativeCapabilities = [
  { icon: Film, title: "Video Editing", text: "I enjoy shaping engaging videos through storytelling, pacing, visual flow, timing, music, sound and audience-focused presentation. I have contributed to college creative productions and skits through video editing, helping transform raw footage into engaging visual stories." },
  { icon: PenTool, title: "Thumbnail Design", text: "I understand how thumbnails influence attention and first impressions. My approach focuses on composition, visual hierarchy, readability, emotion and communicating content instantly." },
  { icon: Image, title: "Photo & Visual Editing", text: "I explore composition, image enhancement, colour, visual presentation and creative editing to make images communicate an idea or feeling clearly." },
  { icon: Sparkles, title: "Content & Storytelling", text: "I am interested in how content connects with people — exploring visual storytelling, content ideas, content writing and audience-focused communication." },
];
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] } } };

function SectionHeading({ eyebrow, title, note }) { return <motion.div className="section-heading" initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .35 }} transition={{ duration: .65 }}><span className="eyebrow">{eyebrow}</span><h2 data-testid={`${eyebrow.toLowerCase().replaceAll(" ", "-")}-heading`}>{title}</h2>{note && <p>{note}</p>}</motion.div>; }

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [nightMode, setNightMode] = useState(false);
  const [cursorMode, setCursorMode] = useState("");
  const [sent, setSent] = useState("");
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30 });
  useEffect(() => { const move = (e) => { document.documentElement.style.setProperty("--mx", `${e.clientX}px`); document.documentElement.style.setProperty("--my", `${e.clientY}px`); }; const over = (e) => { const target = e.target.closest("a, button, input, textarea"); if (target) setCursorMode(target.dataset.cursorLabel || (target.tagName === "BUTTON" ? "CLICK" : "OPEN")); }; const out = (e) => { if (!e.relatedTarget?.closest?.("a, button, input, textarea")) setCursorMode(""); }; window.addEventListener("pointermove", move); document.addEventListener("pointerover", over); document.addEventListener("pointerout", out); return () => { window.removeEventListener("pointermove", move); document.removeEventListener("pointerover", over); document.removeEventListener("pointerout", out); }; }, []);
  const submit = async (e) => { e.preventDefault(); setSent("sending"); try { await axios.post(`${API}/contact`, form); setSent("success"); setForm({ name: "", email: "", subject: "", message: "" }); } catch (error) { setSent(error.response?.data?.detail || "Message delivery failed. Please try again."); } };
  const closeMenu = () => setMenuOpen(false);
  const anchor = (item) => `#${item.toLowerCase().replaceAll(" ", "-")}`;
  return <div className={`site-shell ${nightMode ? "night-mode" : ""}`}>
    <motion.div className="scroll-progress" style={{ scaleX }} /><div className={`cursor-follower ${cursorMode.replaceAll(" ", "-")}`} aria-hidden="true"><span>{cursorMode}</span></div>
    <header className="nav-wrap"><a href="#home" className="brand" data-testid="brand-home-link" data-cursor-label="HOME"><span>VM</span><small>PORTFOLIO / 2026</small></a><button className="menu-toggle" data-testid="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" data-cursor-label="MENU">{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? "nav-links open" : "nav-links"}>{navItems.map((item) => <a key={item} href={anchor(item)} data-testid={`nav-${item.toLowerCase().replaceAll(" ", "-")}-link`} onClick={closeMenu} data-cursor-label="EXPLORE">{item}</a>)}</nav><div className="nav-tools"><button className="theme-toggle" onClick={() => setNightMode(!nightMode)} data-testid="theme-toggle-button" aria-label={nightMode ? "Switch to day mode" : "Switch to night mode"} data-cursor-label="THEME">{nightMode ? <Sun size={16} /> : <Moon size={16} />}<span>{nightMode ? "DAY" : "NIGHT"}</span></button><a className="nav-contact" href="#contact" data-testid="nav-connect-link" data-cursor-label="CONNECT">Let’s talk <ArrowUpRight size={16} /></a></div></header>
    <main>
      <section id="home" className="hero section-pad"><div className="hero-grid"><motion.div initial="hidden" animate="visible" variants={reveal}><div className="status-line"><span className="pulse" /> Open to meaningful opportunities</div><p className="hero-kicker">VADAPALLI MOULI SRI</p><h1>Technology<br />with a <em>creative</em><br />point of view<span>.</span></h1><p className="hero-role">AI & Data Science Undergraduate · Developer · Hackathon Winner · Video Editor · Creative Storyteller</p><p className="hero-copy">I build intelligent solutions and shape ideas into visual stories people can understand, remember and feel.</p><div className="hero-actions"><a href="#creative-studio" className="button button-dark" data-testid="hero-creative-button" data-cursor-label="CREATIVE">Explore my creative work <ArrowUpRight size={17} /></a><a href="#projects" className="text-link" data-testid="hero-projects-button" data-cursor-label="PROJECTS">See technical work <span>↗</span></a></div></motion.div><motion.div className="hero-orbit" initial={{ opacity: 0, scale: .8 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.2 }}><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><span>AI</span><small>DATA<br />+<br />STORY</small></div><div className="orbit-label label-one">BUILD + TELL</div><div className="orbit-label label-two">CURIOUS BY NATURE</div></motion.div></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><ChevronDown size={17} /><span className="hero-index">01 — 09</span></div></section>
      <section id="about" className="section-pad about"><SectionHeading eyebrow="01 / ABOUT ME" title="More than one discipline." note="Technology is how I build. Creativity is how I tell stories." /><div className="about-layout"><motion.div className="about-copy" whileInView="visible" initial="hidden" variants={reveal}><p className="large-copy">I’m Mouli, an <strong>AI & Data Science</strong> undergraduate, developer and creative storyteller who enjoys moving between systems and stories.</p><p>I am pursuing my B.Tech at Amrita Vishwa Vidyapeetham, Coimbatore. I enjoy solving problems through software, exploring intelligent systems and learning how data can create impact.</p><p>Alongside technology, I have developed practical understanding in video editing, thumbnail design, photo editing, content creation, visual storytelling and content writing.</p></motion.div><div className="identity-pair"><div data-testid="identity-technical"><span className="identity-number">01</span><h3>AI &<br />Data Science</h3><p>Systems, patterns, possibilities.</p></div><div data-testid="identity-creative"><span className="identity-number">02</span><h3>Creative<br />Communication</h3><p>Images, motion, meaning.</p></div></div></div></section>
      <section id="skills" className="section-pad skills"><SectionHeading eyebrow="02 / PROFESSIONAL IDENTITY" title="Two ways of thinking. One way of working." note="I bring technical problem-solving and creative communication into the same process." /><div className="identity-capabilities"><div><span className="skill-index">TECHNICAL CAPABILITY</span><h3>Build intelligent<br />solutions.</h3><p>AI · Data Science · Software Development · Problem Solving · Data Visualization</p></div><div><span className="skill-index">CREATIVE CAPABILITY</span><h3>Make ideas<br />connect.</h3><p>Video Editing · Thumbnail Design · Photo Editing · Content Creation · Storytelling · Content Writing</p></div></div><div className="skill-grid">{skillGroups.map(([title, ...skills], i) => <div className="skill-group" key={title}><span className="skill-index">0{i + 1}</span><h3>{title}</h3><div>{skills.map(skill => <span key={skill} data-testid={`skill-${skill.toLowerCase().replaceAll(" ", "-")}`}>{skill}</span>)}</div></div>)}</div></section>
      <section id="creative-studio" className="section-pad creative-studio"><div className="studio-top"><SectionHeading eyebrow="03 / CREATIVE & CONTENT STUDIO" title="Creating beyond code." note="Technology is how I build. Creativity is how I tell stories." /><a href="https://www.instagram.com/m.creatix25/" target="_blank" rel="noreferrer" className="studio-cta" data-testid="studio-instagram-cta" data-cursor-label="VIEW INSTAGRAM"><span>Want to see my creative work?</span><strong>View @m.creatix25 <ArrowUpRight size={18} /></strong><small>Opens my editing page <Instagram size={14} /></small></a></div><div className="studio-intro"><p>Alongside my journey in AI and technology, I have developed a strong interest and practical understanding of visual content creation. From video editing and thumbnail design to storytelling and content creation, I enjoy transforming ideas into engaging visual experiences.</p></div><div className="creative-capability-grid">{creativeCapabilities.map(({ icon: Icon, title, text }, i) => <motion.article className="creative-capability" key={title} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={{ hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { delay: i * .08, duration: .55 } } }}><span className="creative-icon"><Icon size={21} /></span><span className="skill-index">0{i + 1}</span><h3>{title}</h3><p>{text}</p></motion.article>)}</div><div className="studio-tools"><span className="skill-index">EDITING TOOLS</span><h3>Tools for shaping the frame.</h3><div>{["Final Cut Pro", "VN", "Creative workflows", "Visual composition"].map(tool => <span key={tool} data-testid={`creative-tool-${tool.toLowerCase().replaceAll(" ", "-")}`}>{tool}</span>)}</div></div><div className="thumbnail-stage" data-testid="thumbnail-gallery-ready"><div className="thumbnail-copy"><span className="skill-index">THUMBNAIL DESIGN / SELECTED WORK READY</span><h3>Strong first impressions<br /><em>start here.</em></h3><p>A gallery space for recreated thumbnails and future selected work — built around composition, hierarchy, readability and emotion.</p></div><div className="thumbnail-stack"><div className="thumb-card thumb-back">VISUAL<br />STORY</div><div className="thumb-card thumb-front"><Play size={20} /><strong>RECREATED<br />THUMBNAIL</strong><small>@m.creatix25</small></div></div></div></section>
      <section id="projects" className="section-pad projects"><SectionHeading eyebrow="04 / TECHNICAL WORK" title="From visual storytelling to technical problem-solving." note="Two sides of the same creative process — making ideas clear, useful and real." /><div className="project-list">{projects.map((project, i) => <motion.article className={`project project-${project.accent}`} key={project.no} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={{ hidden: { opacity: 0, y: 32 }, visible: { opacity: 1, y: 0, transition: { delay: i * .08, duration: .65 } } }}><div className="project-no">{project.no}</div><div className="project-body"><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.desc}</p>{project.flow && <div className="project-flow">{project.flow}</div>}<div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="project-action">{project.href ? <a href={project.href} target="_blank" rel="noreferrer" data-testid={`project-${project.no}-github-link`} aria-label={`Open ${project.title} on GitHub`}><Github size={19} /></a> : <span className="project-mark">↗</span>}</div></motion.article>)}</div><div className="section-cta"><a href="https://github.com/vadapallimouli" target="_blank" rel="noreferrer" className="text-link" data-testid="all-projects-github-link">Explore all projects on GitHub <ArrowUpRight size={17} /></a></div></section>
      <section id="achievements" className="achievement section-pad"><div className="achievement-orbit">✦</div><SectionHeading eyebrow="05 / HACKATHON ACHIEVEMENT" title="24 hours. One idea. 1st Prize." /><div className="achievement-grid"><div className="achievement-number">01<span>ST<br />PRIZE</span></div><div><span className="project-type">HACKATHON WINNER</span><h3>NitroStack<br /><em>24-Hour Hackathon</em></h3><p><strong>BFSI & FinTech Stream</strong> · Team Code Crafters</p></div></div><div className="hackathon-steps"><span>24 HOURS</span><b>→</b><span>IDEA</span><b>→</b><span>BUILD</span><b>→</b><span>INNOVATE</span><b>→</b><strong>1ST PRIZE</strong></div><div className="achievement-story" data-testid="hackathon-story"><span className="project-type">THE PROBLEM WE TOOK ON</span><p>Why should staying safe from a digital scam require technical knowledge? ScamShield: India’s AI-powered Jan Suraksha Bot makes protection as simple as forwarding a message.</p><p>When a suspicious bank alert, KYC message, OTP request, phishing attempt or URL arrives through WhatsApp or SMS, people can forward it to ScamShield — without installing an app, creating an account or understanding technical warnings.</p></div><div className="achievement-foot"><span>HIGH-PRESSURE PROBLEM SOLVING · TEAM COLLABORATION · AI-POWERED INNOVATION</span><span>🏆</span></div></section>
      <section id="experience" className="section-pad experience"><SectionHeading eyebrow="06 / INTERNSHIP & EXPERIENCE" title="Learning in the real world." /><div className="timeline-item"><div className="timeline-date">2025<br />VIRTUAL</div><div><span className="project-type">DELOITTE · DATA ANALYTICS</span><h3>Data Analytics Virtual Internship</h3><p>Worked through data analytics and business problem-solving concepts, exploring analysis, visualization and data-driven decision making with real-world datasets.</p></div><span className="timeline-dot" /></div></section>
      <section id="education" className="section-pad education"><SectionHeading eyebrow="07 / EDUCATION" title="A foundation in progress." /><div className="education-line"><span className="education-year">2025—29</span><div><span className="project-type">BACHELOR OF TECHNOLOGY · PURSUING</span><h3>Artificial Intelligence<br />& Data Science</h3><p>Amrita Vishwa Vidyapeetham, Coimbatore</p><span className="education-note">First year successfully completed · Programming · Data Structures · Mathematics · AI Fundamentals · Data Analytics</span></div></div></section>
      <section id="certifications" className="section-pad certifications"><SectionHeading eyebrow="08 / CERTIFICATIONS" title="Learning that keeps moving." note="Certification details are available through my professional profile." /><a className="linkedin-cert" href="https://www.linkedin.com/in/mouli-vadapalli-7010b23aa" target="_blank" rel="noreferrer" data-testid="certifications-link" data-cursor-label="LINKEDIN"><Linkedin size={22} /><span>View certifications on LinkedIn</span><ArrowUpRight size={18} /></a></section>
      <section id="contact" className="section-pad contact"><div className="contact-head"><SectionHeading eyebrow="09 / CONTACT" title="Let’s build something meaningful." note="Fill in the form and your message will be sent directly to Mouli’s inbox." /></div><div className="contact-layout"><form onSubmit={submit} className="contact-form" data-testid="contact-form"><label>Name<input required minLength="2" data-testid="contact-name-input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" data-testid="contact-email-input" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Subject<input required data-testid="contact-subject-input" value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="What’s on your mind?" /></label><label>Message<textarea required minLength="10" data-testid="contact-message-input" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell me a little about it..." /></label><button className="button button-dark" type="submit" disabled={sent === "sending"} data-testid="contact-submit-button" data-cursor-label="SEND">{sent === "sending" ? "Sending..." : "Send message"}<Send size={16} /></button>{sent && sent !== "sending" && <p className={sent === "success" ? "form-status success" : "form-status error"} data-testid="contact-form-status">{sent === "success" ? "Thanks — your message is on its way." : sent}</p>}</form><div className="contact-aside"><span>MESSAGE DESTINATION</span><p className="contact-destination">vadapallimouli2008@gmail.com</p><div className="social-links"><a href="https://github.com/vadapallimouli" target="_blank" rel="noreferrer" data-testid="footer-github-link" data-cursor-label="GITHUB"><Github /></a><a href="https://www.linkedin.com/in/mouli-vadapalli-7010b23aa" target="_blank" rel="noreferrer" data-testid="footer-linkedin-link" data-cursor-label="LINKEDIN"><Linkedin /></a><a href="https://www.instagram.com/m.creatix25/" target="_blank" rel="noreferrer" data-testid="footer-instagram-link" data-cursor-label="INSTAGRAM"><Instagram /></a></div><span className="languages">English · Telugu</span></div></div></section>
    </main><footer><a href="#home" className="brand" data-testid="footer-home-link"><span>VM</span><small>VADAPALLI MOULI SRI</small></a><p>Built with curiosity, technology and creativity.</p><a href="#home" className="back-top" data-testid="back-to-top-link">Back to top ↑</a><small>© 2026 Vadapalli Mouli Sri</small></footer>
  </div>;
}
export default App;